logging:
  level:
    com.sttl.hrms.workflow: DEBUG
    org.springframework: INFO
    org.springframework.statemachine: DEBUG
    org.springframework.statemachine.support: DEBUG
    org.springframework.statemachine.support.AbstractStateMachine: DEBUG
    org.springframework.statemachine.support.LifecycleObjectSupport: DEBUG
    org.springframework.statemachine.support.ReactiveStateMachineExecutor: DEBUG
    org.springframework.statemachine.support.ReactiveLifecycleManager: DEBUG

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    username: sa
    password:
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none # enable schema file based schema creation
    open-in-view: false
    properties:
      hibernate.hbm2ddl.extra_physical_table_types: PARTITIONED TABLE
    show-sql: true
  main:
    lazy-initialization: false
  sql:
    init:
      mode: embedded